### ISSUE TITLE
Doesn't work with SVN over HTTP?

### ISSUE THREAD

**Issue by FlorianHeigl** [mariusae/trickle#6]
Hi,

we just tried to use trickle to bw limit a periodic SVN checkout.
For some reason, our tests with i.e. wget and http work just fine, limiting to i.e. 10KB/s. But doing the same with SVN has no effect.

I have no idea why this happens...

**Comment by ivanbaldo** [comment]
@FlorianHeigl can you run the same but with trickled first and then trickle connecting to it?
Should work that way...
If it works please close this bug afterwards or just confirm it doesn't work yet.
Thanks a lot!

**Comment by FlorianHeigl** [comment]
@ivanbaldo i'm very sorry, but I don't even remember where I worked and what I accessed when I really had that issue. Unable to reproduce... I'll just close it.
